name: CI
on:
  push:
    branches:
      - ubuntu-2204-testing

jobs:
  test-ubuntu22:
    name: Project Checks
    runs-on: [ubuntu-22.04, ubuntu-24.04]
    timeout-minutes: 5

    steps:

      - name: Test ip6
        run: ip6tables --set-xmark 0x2000/0x2000 --wait
