name: CI
on:
  push:
    branches:
      - test-matrix

jobs:
  test-matrix-jobs:
    name: Test Matrix include
    runs-on: ubuntu-22.04
    timeout-minutes: 5


    strategy:
      fail-fast: false
      matrix:
        box: [almalinux/8, almalinux/9, fedora/cloudbase]
        include:
          - box: almalinux/8
            runtime: runtime.v1
          - box: almalinux/8
            runtime: io.runtime.v1

    steps:

      - name: Test matrix
        run: |
          echo ${{ matrix.box }} - ${{ matrix.runtime }}
